name: Download

on:
  push:
    paths:
    - 'autorun/**'
    - 'autorun-shared/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  upload64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build DLL
      run: |
        rustup default nightly
        cd autorun
        cargo build --release --verbose
        cd ..
        move target/release/autorun.dll gmsv_autorun_win64.dll

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: Windows 64 Bit
        path: gmsv_autorun_win64.dll

  # In the future make this run on an x86 machine https://github.com/actions/runner/issues/423
  upload86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build DLL
      run: |
        rustup default nightly
        rustup target add i686-pc-windows-msvc
        cd autorun
        cargo build --release --verbose --target=i686-pc-windows-msvc
        cd ..
        move target/i686-pc-windows-msvc/release/autorun.dll gmsv_autorun_win32.dll

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: Windows 32 Bit
        path: gmsv_autorun_win32.dll

  upload64_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build DLL
      run: |
        cd autorun
        cargo build --release --verbose
        cd ..
        mv target/release/libautorun.so gmsv_autorun_linux64.dll

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: Linux 64 Bit
        path: gmsv_autorun_linux64.dll

  upload86_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build DLL
      run: |
        sudo apt-get update && sudo apt-get install gcc-multilib
        rustup target add i686-unknown-linux-gnu
        cd autorun
        cargo build --release --verbose --target=i686-unknown-linux-gnu
        cd ..
        mv target/i686-unknown-linux-gnu/release/libautorun.so gmsv_autorun_linux32.dll

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: Linux 32 Bit
        path: gmsv_autorun_linux32.dll
